# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e4f99ebeff245e20907ef2a0b93420fecd65543ddbb36af073477014320f2bb899ebf6528262462697dfb2b1b7ed3e09e9ba95003cae74b8452f8b27f92ac52

test:
  secret_key_base: c9a94930b859aa58e0f0c7a6718748a057b6277cb8834d6f60c7d9aa8e9b57fd3b31ac6c2bef72fc486501549ad477e589d840df9dd42daee6dbcbd96a0b2397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
